Sandstorm:
  UserManagement:
    # Validity timespan for the activation token for newly registered users.
    activationTokenTimeout: '2 days'
    # Validity timespan for the token used to reset passwords.
    resetPasswordTokenTimeout: '4 hours'
    # The message that appears if a user could not be logged in.
    # Set the value to 'i18n' to enable translations
    # using 'authFailedMessage.title and authFailedMessage.body as id.
    authFailedMessage:
      title: 'Login nicht möglich'
      body: 'Sie haben ungültige Zugangsdaten eingegeben. Bitte versuchen Sie es noch einmal.'
    # Email settings
    # Set the value to 'i18n' to enable translations
    # using 'email.subjectActivation' and 'email.subjectResetPassword' as id.
    email:
      subjectActivation: 'Please confirm your account'
      # Subject line for the password reset email
      subjectResetPassword: 'Password reset'
    # An array of roles which are assigned to users after they activate their account.
    rolesForNewUsers: []

    # You can make constraints on allowed passwords here.
    passwordConstraints:
      minLength: 8
      maxLength: 128
      # per default, we do not prescribe anything about the password content - feel free to change these.
      # make sure that the sum of these values does not exceed the minLength, otherwise users can't register.
      minNumberOfLowercaseLetters: 0
      minNumberOfUppercaseLetters: 0
      minNumberOfNumbers: 0
      minNumberOfSpecialCharacters: 0

    # Redirect settings after logout/login
    redirect:
      afterLogin: []
      afterLogout: []
    # To activate redirection, make these settings. controllerArguments are optional.
#      afterLogin:
#        action: 'action'
#        controller: 'Controller'
#        package: 'Your.Package'
#        controllerArguments:
#          yourAdditionalArgument: 'test'
#      afterLogout:
#        action: 'action'
#        controller: 'Controller'
#        package: 'Your.Package'
#        controllerArguments:
#          yourAdditionalArgument: 'test1'

  TemplateMailer:
    templatePackages:
      99999: 'Sandstorm.UserManagement'
    senderAddresses:
      'sandstorm_usermanagement_sender_email':
        name: 'Sandstorm Usermanagement Package'
        address: 'test@example.com'
    replyToAddresses:
      'sandstorm_usermanagement_replyTo_email':
        name: 'Sandstorm Usermanagement Package Reply-To Email'
        address: 'test@example.com'

Neos:
  Flow:
    mvc:
      routes:
        'Sandstorm.UserManagement': TRUE


#   The auth provider settings below are needed for the standalone case only.
    security:
      authentication:
        providers:
          'Sandstorm.UserManagement:Login':
            provider: 'PersistedUsernamePasswordProvider'
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package': 'Sandstorm.UserManagement'
                '@controller': 'Login'
                '@action': 'login'

  Neos:
    fusion:
      autoInclude:
        'Sandstorm.UserManagement':
          position: 'before Neos.Neos'

    userInterface:
      translation:
        autoInclude:
          'Sandstorm.UserManagement': ['NodeTypes/*']
